download artifact

diff --git a/.github/workflows/terraform_apply.yaml b/.github/workflows/terraform_apply.yaml
--- a/.github/workflows/terraform_apply.yaml
+++ b/.github/workflows/terraform_apply.yaml
@@ -104,62 +104,78 @@ jobs:
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/${{ github.repository }}/deployments/${{ steps.list_deployments.outputs.deployment_id }})
+          echo "run-id=$(echo $response | jq -r '.payload | fromjson | ."run-id"')" >> $GITHUB_OUTPUT
+          echo "artifact-name=$(echo $response | jq -r '.payload | fromjson | ."artifact-name"')" >> $GITHUB_OUTPUT
+          echo "artifact-id=$(echo $response | jq -r '.payload | fromjson | ."artifact-id"')" >> $GITHUB_OUTPUT
 
-      - name: Fetch PR reviews
-        id: fetch_pr_reviews
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Download Terraform artifacts
+        uses: actions/download-artifact@v4
+        with:
+          run-id: ${{ steps.get_plan_deployment.outputs.run-id }}
+          name: ${{ steps.get_plan_deployment.outputs.artifact-name }}
+          path: ${{ inputs.working-directory }}
+
+      - name: delete terraform artifact
+        id: delete_artifact
         run: |
-          pr_reviews=$(gh pr review list -R "${{ inputs.repo }}" -p "${{ inputs.pr_number }}" | jq '.')
-          echo "pr_reviews=$pr_reviews" >> $GITHUB_OUTPUT
-
-
-      - name: Check for code owner approval
-        id: check_approval
-        run: |
-          pr_reviews="${{ steps.fetch_pr_reviews.outputs.pr_reviews }}"
-          code_owner_approval=false
-          # Fetch the list of code owners
-          code_owners=$(gh api repos/${{ inputs.repo }}/contents/.github/CODEOWNERS | jq -r '.content' | base64 --decode | grep -Eo '@\w+' | tr -d '@')
-
-          for row in $(echo "${pr_reviews}" | jq -r '.[] | @base64'); do
-            review="$(echo ${row} | base64 --decode)"
-            state=$(echo "${review}" | jq -r '.state')
-            user_login=$(echo "${review}" | jq -r '.user.login')
-
-            if [ "${state}" == "APPROVED" ]; then
-              if echo "${code_owners}" | grep -wq "$user_login"; then
-                code_owner_approval=true
-                break
-              fi
-            fi
-          done
-
-          # Check if the user who made the comment is a code owner
-          commenter="${{ github.event.comment.user.login }}"
-          if echo "${code_owners}" | grep -wq "$commenter"; then
-            code_owner_approval=true
-          fi
-
-          if [ "${code_owner_approval}" == "false" ]; then
-            comment_body="error: PR not approved by a code owner. A code owner approval is required to trigger 'terraform apply'."
-            comment_payload=$(jq -n --arg body "$comment_body" '{"body": $body}')
-            gh api repos/${{ inputs.repo }}/issues/${{ inputs.pr_number }}/comments -H "Content-Type: application/json" -d "$comment_payload"
-            exit 1
-          fi
-          echo "code_owner_approval=$code_owner_approval" >> $GITHUB_OUTPUT
-
-
-      - name: Validate that the plan has been approved
-        id: validate_plan_approval
-        run: |
-          if [ "${{ inputs.operation }}" == "apply" ]; then
-            if [ "${{ steps.check_approval.outputs.code_owner_approval }}" == "false" ]; then
-              echo "error: PR not approved by a code owner" >&2
-              exit 1
-            fi
-          fi
+          gh api repos/${{ inputs.repo }}/actions/artifacts/${{ steps.get_plan_deployment.outputs.artifact-id }} -X DELETE
         continue-on-error: false
+
+#      - name: Fetch PR reviews
+#        id: fetch_pr_reviews
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          pr_reviews=$(gh pr review list -R "${{ inputs.repo }}" -p "${{ inputs.pr_number }}" | jq '.')
+#          echo "pr_reviews=$pr_reviews" >> $GITHUB_OUTPUT
+#
+#
+#      - name: Check for code owner approval
+#        id: check_approval
+#        run: |
+#          pr_reviews="${{ steps.fetch_pr_reviews.outputs.pr_reviews }}"
+#          code_owner_approval=false
+#          # Fetch the list of code owners
+#          code_owners=$(gh api repos/${{ inputs.repo }}/contents/.github/CODEOWNERS | jq -r '.content' | base64 --decode | grep -Eo '@\w+' | tr -d '@')
+#
+#          for row in $(echo "${pr_reviews}" | jq -r '.[] | @base64'); do
+#            review="$(echo ${row} | base64 --decode)"
+#            state=$(echo "${review}" | jq -r '.state')
+#            user_login=$(echo "${review}" | jq -r '.user.login')
+#
+#            if [ "${state}" == "APPROVED" ]; then
+#              if echo "${code_owners}" | grep -wq "$user_login"; then
+#                code_owner_approval=true
+#                break
+#              fi
+#            fi
+#          done
+#
+#          # Check if the user who made the comment is a code owner
+#          commenter="${{ github.event.comment.user.login }}"
+#          if echo "${code_owners}" | grep -wq "$commenter"; then
+#            code_owner_approval=true
+#          fi
+#
+#          if [ "${code_owner_approval}" == "false" ]; then
+#            comment_body="error: PR not approved by a code owner. A code owner approval is required to trigger 'terraform apply'."
+#            comment_payload=$(jq -n --arg body "$comment_body" '{"body": $body}')
+#            gh api repos/${{ inputs.repo }}/issues/${{ inputs.pr_number }}/comments -H "Content-Type: application/json" -d "$comment_payload"
+#            exit 1
+#          fi
+#          echo "code_owner_approval=$code_owner_approval" >> $GITHUB_OUTPUT
+#
+#
+#      - name: Validate that the plan has been approved
+#        id: validate_plan_approval
+#        run: |
+#          if [ "${{ inputs.operation }}" == "apply" ]; then
+#            if [ "${{ steps.check_approval.outputs.code_owner_approval }}" == "false" ]; then
+#              echo "error: PR not approved by a code owner" >&2
+#              exit 1
+#            fi
+#          fi
+#        continue-on-error: false
 
       - name: configure aws credentials
         id: configure-aws-credentials
@@ -183,10 +199,6 @@ jobs:
           ref:  refs/pull/${{ inputs.pr_number }}/head
           repository: ${{ inputs.repo }}
 
-      - name: Download Terraform artifacts
-        uses: actions/download-artifact@v4
-        with:
-          run-id: ${{ github.run_id }}
 
       - name: Add PR comment if Download Terraform artifacts fails
         if: ${{ failure() && steps.download-artifact.outcome == 'failure' }}
@@ -199,20 +211,7 @@ jobs:
           exit 1
         continue-on-error: false
 
-      - name: Get and Delete Artifacts
-        id: get-and-delete-artifacts
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          artifact_name="${{ steps.setup.outputs.artifact_name }}"
-          artifact_data=$(gh api repos/${{ inputs.repo }}/actions/artifacts)
-          artifact_ids=$(echo "$artifact_data" | jq -r ".artifacts[] | select(.name == \"$artifact_name\") | .id")
 
-          for artifact_id in $artifact_ids; do
-            echo "Deleting artifact with ID: $artifact_id"
-            gh api repos/${{ inputs.repo }}/actions/artifacts/$artifact_id -X DELETE
-          done
-        continue-on-error: false
 
 
       - name: install sops
